### PR TITLE
Check if FirewallD is installed before running ks firewall commands

### PR DESCRIPTION
**Pull request by kkofler**
It is possible for a live image to be built without FirewallD installed in the target, either for the purpose of not configuring a firewall or for the purpose of using an alternative.

So, now we check for if `firewall-offline-cmd` is installed. If it is not, then we throw a warning and ignore the configuration commands.

### CODE REVIEW

**Comment by kkofler** [comment]
Ping? Are you looking at this one too? This can go in before or after the DNF port, it does not conflict either way.

I need this for my Kannolo Fedora Remix (that uses UFW), Mageia uses Shorewall and also wants this, and if anybody wants to build Fedora Cloud with the livecd-tools (rather than livemedia-creator) for some reason, that one installs no firewall at all and so also wants it. (Fedora Cloud and Kannolo both used to have an ugly workaround where they installed firewalld in %packages and removed it in %post.)

The change makes no difference for kickstarts using firewalld, it only fixes a case that would otherwise produce an error.

**Comment by Conan-Kudo** [comment]
@bcl Could you please review and see if this can be merged in?

**Comment by kkofler** [comment]
I rebased the commit onto the current master (no changes were needed).

**Comment by bcl** [comment]
Addressed by #40

**Pull request closed without merging**
