### PR TITLE
Port from yum to dnf, add Python 3 support

### PR DESCRIPTION
**Pull request by kkofler**
* Port from yum to dnf. Some code lifted from the Anaconda dnfpayload.py (compatibly licensed).
* Also handle the excludeWeakdeps kickstart flag.
* Port from legacy Python 2 (only) to Python 2.6+, 3.3+ (Neal Gompa).
* Add support for `make PYTHON=python3` (Neal Gompa).
* Bump version to 24.0 (Neal Gompa).

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
I've made preliminary package builds of livecd-tools on COPR based on this new code as well: https://copr.fedorainfracloud.org/coprs/ngompa/livecd-creator/

**Comment by bcl** [comment]
Thanks, I'll try to review this sometime this week. The version number should match the Fedora release that it functions with, so 24 is fine as long as it works with >= F24

**Comment by Conan-Kudo** [comment]
@bcl It does, and it will work for F25+ as well.

**Comment by kkofler** [comment]
F24 is what I have tested it on. It can generate ISOs for at least F23 (tested on a F24 host though) and F24, and indeed, I expect it to work for F25+ as well (but I have not tested that yet, only up to F24).

By the way, the code should already be prepared for DNF 2.0, I used the DNF 2.0 docs as the reference, and in the one place where the API differs from the DNF 1.1.x that I tried with, I support both. But so far, it is only tested on F24's DNF 1.1.10.

**Comment by bcl** [comment]
What version of pykickstart are you testing with? I ran into a problem with get_modules -- in F24 and later the device command is deprecated so either get_modules needs to go away, or it needs to exit with [] if ks.handler.device.seen is false.

I'd also suggest making a final pass thru the code and updating all the references to 'yum' to dnf or 'dbo' (dnf base object).

Other than that, this looks ok to me. Thanks for all the work.

**Comment by kkofler** [comment]
I am testing with python3-kickstart-2.25-4.fc24 and python-kickstart-2.25-4.fc24. The only deprecation warning I have seen comes from pykickstart itself using its own deprecated API (/usr/lib64/python2.7/optparse.py:1013: PendingDeprecationWarning: The KSOption class is deprecated and will be removed in pykickstart-3.  Use the argparse module instead.) which is only called from pykickstart's own modules.

**Comment by Conan-Kudo** [comment]
@bcl I've changed all the Yum references over to DNF, and @kkofler has verified everything is fine with it.

Are we good for merge, now?

**Comment by bcl** [comment]
I'd like to merge this to master only at first -- I'm not sure if this should be backported to released versions yet -- we should check with dgilmore, etc. to be sure it doesn't cause problems.

In pykickstart versions > 3.1 get_modules is going to need to be changed or removed. I'd suggest removing it since I don't think it has ever seen regular usage. It should also be tested with F25 and rawhide to be sure there are no other surprises.

**Comment by Conan-Kudo** [comment]
@bcl There's no F24 branch currently, so technically it'd go into master and be branched into `f24-branch`.

Fedora does not offer pykickstart 3.0+ in Rawhide, only 2.33. Fedora 25 has pykickstart 2.32.

I'm running through an ISO build right now on Fedora 25 to verify it still works (it worked the last time I tried).

**Comment by bcl** [comment]
Right, what I mean is the version available in F24. I never branched because focus has changed to livemedia-creator. I hadan't realized that pykickstart3 wasn't released for Fedora yet. So that's a non-issue for now.

**Comment by Conan-Kudo** [comment]
@bcl Thanks!

**Comment by kkofler** [comment]
Thanks for merging this!

You may want to change the description on the https://github.com/rhinstaller/livecd-tools front page, it still says "Tools for building live CDs using yum".

**Pull request merged**
